if not exist "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx" mkdir "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx"

echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\adocfile.doc" 
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\adocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aadocfile.doc"
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aadocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aaadocfile.doc"
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aaadocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\0docfile.doc"
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\0docfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\01docfile.doc"
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\01docfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\02docfile.doc"
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\02docfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zdocfile.doc"
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zdocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.doc"
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.doc"
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\adocfile.pdf""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\adocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aadocfile.pdf""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aadocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aaadocfile.pdf""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aaadocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\0docfile.pdf""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\0docfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\01docfile.pdf""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\01docfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\02docfile.pdf""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\02docfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zdocfile.pdf""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zdocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.pdf""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.pdf""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\adocfile.xls""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\adocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aadocfile.xls""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aadocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aaadocfile.xls""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\aaadocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\0docfile.xls""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\0docfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\01docfile.xls""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\01docfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\02docfile.xls""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\02docfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zdocfile.xls""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zdocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.xls""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.doc"
echo.>"C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.xls""
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx\zzdocfile.doc"
attrib +h "C:\users\%USERNAME%\aaaaa_honeypot_1qaz2wsx"

if not exist "C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx" mkdir "C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx"

echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\adocfile.doc"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\aadocfile.doc"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\aaadocfile.doc"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\0docfile.doc"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\01docfile.doc"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\02docfile.doc"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\zdocfile.doc"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\zzdocfile.doc"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\zzdocfile.doc"

echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\adocfile.pdf"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\aadocfile.pdf"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\aaadocfile.pdf"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\0docfile.pdf"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\01docfile.pdf"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\02docfile.pdf"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\zdocfile.pdf"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\zzdocfile.pdf"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\zzdocfile.pdf"

echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\adocfile.xls"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\aadocfile.xls"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\aaadocfile.xls"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\0docfile.xls"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\01docfile.xls"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\02docfile.xls"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\zdocfile.xls"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\zzdocfile.xls"
echo.>"C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx\zzdocfile.xls"

attrib +h "C:\users\%USERNAME%\zzzzz_honeypot_1qaz2wsx" /s 

if not exist "C:\users\%USERNAME%\00000_honeypot_1qaz2wsx" mkdir "C:\users\%USERNAME%\00000_honeypot_1qaz2wsx"

echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\adocfile.doc"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\aadocfile.doc"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\aaadocfile.doc"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\0docfile.doc"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\01docfile.doc"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\02docfile.doc"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\zdocfile.doc"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\zzdocfile.doc"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\zzdocfile.doc"

echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\adocfile.pdf"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\aadocfile.pdf"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\aaadocfile.pdf"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\0docfile.pdf"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\01docfile.pdf"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\02docfile.pdf"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\zdocfile.pdf"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\zzdocfile.pdf"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\zzdocfile.pdf"

echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\adocfile.xls"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\aadocfile.xls"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\aaadocfile.xls"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\0docfile.xls"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\01docfile.xls"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\02docfile.xls"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\zdocfile.xls"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\zzdocfile.xls"
echo.>"C:\users\%USERNAME%\00000_honeypot_1qaz2wsx\zzdocfile.xls"

attrib +h "C:\users\%USERNAME%\00000_honeypot_1qaz2wsx" /s /d